// src/products.js
export const products = [
  {
    id: "1",
    name: "T-shirt 1",
    price: 19.99,
    model: "1.glb",
    description: "This is a stylish T-Shirt made from high-quality cotton.",
  },
  {
    id: "2",
    name: "T-shirt 2",
    price: 24.99,
    model: "2.glb",
    description: "This is a stylish T-Shirt made from high-quality cotton.",
  },
  {
    id: "3",
    name: "T-shirt 3",
    price: 29.99,
    model: "3.glb",
    description: "This is a stylish T-Shirt made from high-quality cotton.",
  },
  {
    id: "4",
    name: "T-shirt 4",
    price: 34.99,
    model: "4.glb",
    description: "This is a stylish T-Shirt made from high-quality cotton.",
  },
  {
    id: "5",
    name: "T-shirt 5",
    price: 39.99,
    model: "5.glb",
    description: "This is a stylish T-Shirt made from high-quality cotton.",
  },
  {
    id: "6",
    name: "T-shirt 6",
    price: 44.99,
    model: "6.glb",
    description: "This is a stylish T-Shirt made from high-quality cotton.",
  },
  {
    id: "7",
    name: "T-shirt 7",
    price: 49.99,
    model: "7.glb",
    description: "This is a stylish T-Shirt made from high-quality cotton.",
  },
  {
    id: "8",
    name: "T-shirt 8",
    price: 54.99,
    model: "8.glb",
    description: "This is a stylish T-Shirt made from high-quality cotton.",
  },
  {
    id: "9",
    name: "T-shirt 9",
    price: 59.99,
    model: "9.glb",
    description: "This is a stylish T-Shirt made from high-quality cotton.",
  },
  {
    id: "10",
    name: "T-shirt 10",
    price: 64.99,
    model: "10.glb",
    description: "This is a stylish T-Shirt made from high-quality cotton.",
  },
  {
    id: "11",
    name: "T-shirt 11",
    price: 0,
    model: "10.glb",
    description: "This is a stylish T-Shirt made from high-quality cotton.",
  },
];
